<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IranRiskTracker.Application\IranRiskTracker.Application.csproj" />
    <ProjectReference Include="..\IranRiskTracker.Domain\IranRiskTracker.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Seed\data\" />
  </ItemGroup>

</Project>
