<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IranRiskTracker.Application\IranRiskTracker.Application.csproj" />
    <ProjectReference Include="..\IranRiskTracker.Domain\IranRiskTracker.Domain.csproj" />
    <ProjectReference Include="..\IranRiskTracker.Infrastructure\IranRiskTracker.Infrastructure.csproj" />
  </ItemGroup>

</Project>
